### ISSUE TITLE
Configure extension with closure

### ISSUE THREAD

**Issue by PetrHudik** [contributte/facebook#5]
Hello, 

I'm using probably weird configuration in my neon file:

```yaml
extensions:
    facebook: Contributte\Facebook\DI\Nette\FacebookExtension

facebook:
    appId: @webDefinition::getFacebookId()
    appSecret: @webDefinition::getFacebookSecret()
```

I known it is not common way to write configuration, but it works for most extensions I use - and it fails [here](https://github.com/contributte/facebook/blob/master/src/DI/Nette/FacebookExtension.php#L36). Is there any way to change validator to pass this?
